package com.onextel.CallServiceApplication.audit;

public enum AuditEventType {
    CALL_SERVICE_INSTANCE_REGISTERED,
    CALL_SERVICE_INSTANCE_FAILURE_DETECTED,
    CALL_SERVICE_INSTANCE_UNREGISTERED,

    ERROR_OCCURRED,

    CALL_REGISTERED,
    CHANNEL_CREATED,
    CHANNEL_ADDED,
    CHANNEL_ANSWERED,
    CALL_STATE_CHANGED,
    EARLY_MEDIA,
    CHANNEL_STATE_CHANGED,
    DTMF_RECEIVED,
    CHANNEL_BRIDGED,
    CHANNEL_UNBRIDGED,
    CHANNEL_HOLD,
    CHANNEL_UNHOLD,
    CALL_TRANSFER_INITIATED,
    CALL_TRANSFER_COMPLETE,
    CHANNEL_HANGUP,
    CHANNEL_REMOVED,
    CALL_COMPLETED,
    CALL_UNREGISTERED,

    CALL_RECOVERED,
    CALL_RECOVERY_FAILED,

    COMMAND_SENT,
    COMMAND_RESPONSE_RECEIVED
}
